//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DNS cannot resolve {0}.
        /// </summary>
        internal static string DNSResolveErrorFmt {
            get {
                return ResourceManager.GetString("DNSResolveErrorFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send data to server fail..
        /// </summary>
        internal static string ExecuteErrorSendDataFail {
            get {
                return ResourceManager.GetString("ExecuteErrorSendDataFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;UNKNOWN&apos; command could not be executed...
        /// </summary>
        internal static string ExecuteErrorUnknowCommand {
            get {
                return ResourceManager.GetString("ExecuteErrorUnknowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be null..
        /// </summary>
        internal static string NullExceptionFmt {
            get {
                return ResourceManager.GetString("NullExceptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be null or empty..
        /// </summary>
        internal static string NullOrEmptyExceptionFmt {
            get {
                return ResourceManager.GetString("NullOrEmptyExceptionFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port {0} out of the range (0, 65535).
        /// </summary>
        internal static string PortOutOfRangeFmt {
            get {
                return ResourceManager.GetString("PortOutOfRangeFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} property could not be set to null..
        /// </summary>
        internal static string PropertySetNullErrorFmt {
            get {
                return ResourceManager.GetString("PropertySetNullErrorFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read large content fail, the result is null..
        /// </summary>
        internal static string ReaderErrorLargeData {
            get {
                return ResourceManager.GetString("ReaderErrorLargeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not select db: {0}.
        /// </summary>
        internal static string RedisSelectErrorFmt {
            get {
                return ResourceManager.GetString("RedisSelectErrorFmt", resourceCulture);
            }
        }
    }
}
